# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods

    sigh(
      skip_fetch_profiles: false,
      skip_certificate_verification: true,
      skip_install: true)
  end

  lane :development do
    version_string = get_info_plist_value(path: "./hiChat/info.plist", key: "CFBundleShortVersionString")
    version_code = get_info_plist_value(path: "./hiChat/info.plist", key: "CFBundleVersion")

    gym(
      scheme: "hiChat",
      configuration: "Release",
      output_directory: "./build/development",
      output_name: "hiChat-#{version_string}(#{version_code}).ipa",
      silent: true,
      clean: true
    )
  end

  lane :production do
    version_string = get_info_plist_value(path: "./hiChat/info_pub.plist", key: "CFBundleShortVersionString")
    version_code = get_info_plist_value(path: "./hiChat/info_pub.plist", key: "CFBundleVersion")

    gym(
      scheme: "hiChat_pub",
      configuration: "Release",
      output_directory: "./build/production",
      output_name: "hiChat_pub-#{version_string}(#{version_code}).ipa",
      silent: true,
      clean: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "hiChat.xcworkspace", scheme: "hiChat_app_store")
    upload_to_testflight
  end
end
